export const availableIndustries = [
  'All Industries',
  'Tech',
  'IT',
  'Finance',
  'Healthcare',
  'Education',
  'Retail',
  'Real Estate',
  'Marketing',
];

export const availableSkills = [
  'Problem Solving',
  'Conflict Resolution',
  'Adaptability',
  'Decision Making',
];

export const availableLocations = [
  'All Locations',
  'United States',
  'Canada',
  'United Kingdom',
  'Australia',
  'Germany',
  'India',
  'France',
  'Spain',
  'Italy',
  'Netherlands',
  'Brazil',
  'Mexico',
  'Japan',
  'China',
  'South Korea',
  'Russia',
  'South Africa',
  'Singapore',
  'New Zealand',
  'Sweden',
  'Norway',
  'Finland',
  'Denmark',
  'Ireland',
  'Belgium',
  'Switzerland',
  'Austria',
  'Czech Republic',
  'Poland',
  'Portugal',
  'Greece',
  'Turkey',
  'Remote',
];

export const availableRoles = [
  'All Roles',
  'Software Engineer',
  'Data Scientist',
  'Product Manager',
  'UX Designer',
  'Marketing Specialist',
  'Sales Executive',
  'HR Manager',
  'Customer Support',
  'Project Manager',
  'Business Analyst',
  'DevOps Engineer',
  'Web Developer',
  'Mobile Developer',
  'Cybersecurity Analyst',
  'Game Developer',
];

export const experienceRanges = [
  { label: 'All Experience', min: 0, max: 999 },
  { label: '0-1 year', min: 0, max: 1 },
  { label: '2-4 years', min: 2, max: 4 },
  { label: '5-7 years', min: 5, max: 7 },
  { label: '8+ years', min: 8, max: 99 },
];
